# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesLogit_DualNet_FixedAdj <- function(X, y, R_dyn_int, R_fix_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, T_max, proposal_type, thin = 1L, n_thin_gb = 3L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0) {
    .Call(`_BVS_DAdj_BayesLogit_DualNet_FixedAdj`, X, y, R_dyn_int, R_fix_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, T_max, proposal_type, thin, n_thin_gb, beta_in, gamma_in, alpha_in)
}

BayesLogit_DualNet_GGM <- function(X, y, S_ggm, n_ggm, R_fix_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, lambda_ggm, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, e_eta, f_eta, T_max, proposal_type, thin = 1L, n_thin_gb = 3L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0) {
    .Call(`_BVS_DAdj_BayesLogit_DualNet_GGM`, X, y, S_ggm, n_ggm, R_fix_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, lambda_ggm, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, e_eta, f_eta, T_max, proposal_type, thin, n_thin_gb, beta_in, gamma_in, alpha_in)
}

BayesLogit_DualNet_SparseGGM <- function(X, y, S_i, S_p_csc, S_x, S_diag, R_fix_i, R_fix_p_csc, p_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, v0_ggm, v1_ggm, pii_ggm, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, T_max, proposal_type, n_mh_gamma = 5L, thin = 1L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0, store_beta = TRUE, store_gamma = TRUE, store_Z_list = FALSE, store_Z_pip = TRUE) {
    .Call(`_BVS_DAdj_BayesLogit_DualNet_SparseGGM`, X, y, S_i, S_p_csc, S_x, S_diag, R_fix_i, R_fix_p_csc, p_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, v0_ggm, v1_ggm, pii_ggm, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, T_max, proposal_type, n_mh_gamma, thin, beta_in, gamma_in, alpha_in, store_beta, store_gamma, store_Z_list, store_Z_pip)
}

phase_transit_2eta_fixadj <- function(R1, R2, T_max, mu, min_eta, max_eta, num_rep, step_size = 0.01) {
    .Call(`_BVS_DAdj_phase_transit_2eta_fixadj`, R1, R2, T_max, mu, min_eta, max_eta, num_rep, step_size)
}

BayesLogit_PG_DualAdj <- function(X, y, R_glasso_int, R_fix_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, e_eta, f_eta, T_max, proposal_type, thin = 1L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0, eta1_init = 0.01, eta2_init = 0.01, sigmasq_init = 1.0, block_size = 1L, pcg_threshold = 500L) {
    .Call(`_BVS_DAdj_BayesLogit_PG_DualAdj`, X, y, R_glasso_int, R_fix_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, e_eta, f_eta, T_max, proposal_type, thin, beta_in, gamma_in, alpha_in, eta1_init, eta2_init, sigmasq_init, block_size, pcg_threshold)
}

BayesLogit_PG_DualNet_SparseGGM <- function(X, y, S_i, S_p_csc, S_x, S_diag, R_fix_i, R_fix_p_csc, p_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, e_eta, f_eta, T_max, proposal_type, thin = 1L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0, store_beta = TRUE, store_gamma = TRUE, store_Z_list = FALSE, store_Z_pip = TRUE, block_size = 1L, pcg_threshold = 500L) {
    .Call(`_BVS_DAdj_BayesLogit_PG_DualNet_SparseGGM`, X, y, S_i, S_p_csc, S_x, S_diag, R_fix_i, R_fix_p_csc, p_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, e_eta, f_eta, T_max, proposal_type, thin, beta_in, gamma_in, alpha_in, store_beta, store_gamma, store_Z_list, store_Z_pip, block_size, pcg_threshold)
}

phase_transit_2eta <- function(R1, R2, T_max, mu, min_eta, max_eta, num_rep, step_size = 0.01) {
    .Call(`_BVS_DAdj_phase_transit_2eta`, R1, R2, T_max, mu, min_eta, max_eta, num_rep, step_size)
}

BayesLogit_PG_GGM_Moller <- function(X, y, S_ggm, n_ggm, R_fix, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, lambda_ggm, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, e_eta, f_eta, T_max, proposal_type, thin = 1L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0, block_size = 1L, pcg_threshold = 500L) {
    .Call(`_BVS_DAdj_BayesLogit_PG_GGM_Moller`, X, y, S_ggm, n_ggm, R_fix, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, lambda_ggm, eta1_sd, eta2_sd, mu_tilde, eta1_tilde, eta2_tilde, e_eta, f_eta, T_max, proposal_type, thin, beta_in, gamma_in, alpha_in, block_size, pcg_threshold)
}

BayesLogit_PG_SingleAdj <- function(X, y, R_adj_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, eta1_sd, mu_tilde, eta1_tilde, e_eta, f_eta, T_max, proposal_type, thin = 1L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0, eta1_init = 0.01, sigmasq_init = 1.0, block_size = 1L, pcg_threshold = 500L) {
    .Call(`_BVS_DAdj_BayesLogit_PG_SingleAdj`, X, y, R_adj_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, eta1_sd, mu_tilde, eta1_tilde, e_eta, f_eta, T_max, proposal_type, thin, beta_in, gamma_in, alpha_in, eta1_init, sigmasq_init, block_size, pcg_threshold)
}

phase_transit_1eta <- function(R1, T_max, mu, min_eta, max_eta, num_rep, step_size = 0.01) {
    .Call(`_BVS_DAdj_phase_transit_1eta`, R1, T_max, mu, min_eta, max_eta, num_rep, step_size)
}

BayesLogit_PG_SingleAdj_GGM_Moller <- function(X, y, S_ggm, n_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, lambda_ggm, eta1_sd, mu_tilde, eta1_tilde, e_eta, f_eta, T_max, proposal_type, thin = 1L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0, block_size = 1L, pcg_threshold = 500L) {
    .Call(`_BVS_DAdj_BayesLogit_PG_SingleAdj_GGM_Moller`, X, y, S_ggm, n_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, lambda_ggm, eta1_sd, mu_tilde, eta1_tilde, e_eta, f_eta, T_max, proposal_type, thin, beta_in, gamma_in, alpha_in, block_size, pcg_threshold)
}

BayesLogit_PG_SingleAdj_SparseGGM <- function(X, y, S_i, S_p_csc, S_x, S_diag, p_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, eta1_sd, mu_tilde, eta1_tilde, e_eta, f_eta, T_max, proposal_type, thin = 1L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0, store_beta = TRUE, store_gamma = TRUE, store_Z_list = FALSE, store_Z_pip = TRUE, block_size = 1L, pcg_threshold = 500L) {
    .Call(`_BVS_DAdj_BayesLogit_PG_SingleAdj_SparseGGM`, X, y, S_i, S_p_csc, S_x, S_diag, p_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, n_mh_gamma, v0_ggm, v1_ggm, pii_ggm, eta1_sd, mu_tilde, eta1_tilde, e_eta, f_eta, T_max, proposal_type, thin, beta_in, gamma_in, alpha_in, store_beta, store_gamma, store_Z_list, store_Z_pip, block_size, pcg_threshold)
}

BayesLogit_SingleNet_FixedAdj <- function(X, y, R_fix_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, eta1_sd, mu_tilde, eta1_tilde, T_max, proposal_type, thin = 1L, n_thin_gb = 3L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0) {
    .Call(`_BVS_DAdj_BayesLogit_SingleNet_FixedAdj`, X, y, R_fix_int, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, eta1_sd, mu_tilde, eta1_tilde, T_max, proposal_type, thin, n_thin_gb, beta_in, gamma_in, alpha_in)
}

BayesLogit_SingleNet_GGM <- function(X, y, S_ggm, n_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, v0_ggm, v1_ggm, pii_ggm, lambda_ggm, eta1_sd, mu_tilde, eta1_tilde, T_max, proposal_type, thin = 1L, n_thin_gb = 3L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0) {
    .Call(`_BVS_DAdj_BayesLogit_SingleNet_GGM`, X, y, S_ggm, n_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, v0_ggm, v1_ggm, pii_ggm, lambda_ggm, eta1_sd, mu_tilde, eta1_tilde, T_max, proposal_type, thin, n_thin_gb, beta_in, gamma_in, alpha_in)
}

BayesLogit_SingleNet_SparseGGM <- function(X, y, S_i, S_p_csc, S_x, S_diag, p_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, v0_ggm, v1_ggm, pii_ggm, eta1_sd, mu_tilde, eta1_tilde, T_max, proposal_type, n_mh_gamma = 5L, thin = 1L, beta_in = NULL, gamma_in = NULL, alpha_in = 0.0, store_beta = TRUE, store_gamma = TRUE, store_Z_list = FALSE, store_Z_pip = TRUE) {
    .Call(`_BVS_DAdj_BayesLogit_SingleNet_SparseGGM`, X, y, S_i, S_p_csc, S_x, S_diag, p_ggm, niter, burnin, mu, nu0, sigmasq0, alpha0, beta0, h, e_eta, f_eta, v0_ggm, v1_ggm, pii_ggm, eta1_sd, mu_tilde, eta1_tilde, T_max, proposal_type, n_mh_gamma, thin, beta_in, gamma_in, alpha_in, store_beta, store_gamma, store_Z_list, store_Z_pip)
}

